//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMoveoTask
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class moveoTaskDbContext : DbContext
    {
        public moveoTaskDbContext()
            : base("name=moveoTaskDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblCodeBlock> tblCodeBlock { get; set; }
        public virtual DbSet<tblSessins> tblSessins { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
    }
}
