//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMoveoTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCodeBlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCodeBlock()
        {
            this.tblSessins = new HashSet<tblSessins>();
        }
    
        public int BlockId { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public string CorrectCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSessins> tblSessins { get; set; }
    }
}
