//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMoveoTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSessins
    {
        public string SessionId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public string UserId { get; set; }
        public string MentorId { get; set; }
    
        public virtual tblCodeBlock tblCodeBlock { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
